server:
  port: 8001

# mybatis配置
mybatis:
  type-aliases-package: com.loubth.springcloud.pojo
  # 配置“mybatis核心配置文件”的地址。不过这个配置文件很久没写了。
  config-location: classpath:mybatis/mybatis-config.xml
  # 配置“配置文件XXXMapper.xml”的地址
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring的配置
spring:
  application:
    # 给当前spring项目起名，一般名字和子module名字一致或接近
    name: springcloud-provider-dept
  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: loubth
    password: loubth

# Eureka配置：配置服务注册中心地址，该地址要和EurekaServer（即服务注册中心）中配置的一致。子工程会往这个地址注册服务
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  # 修改Eureka上的默认描述信息
  instance:
    instance-id: springcloud-provider-dept-hystrix-8001
    prefer-ip-address: true
# info配置
info:
  app.name: loubthDept
  company.name: loubthCompany

