server:
  port: 3344
spring:
  application:
    name: springcloud-config-server
  # 连接远程仓库,具体有哪些属性可以配置可以在springcloud的官网上看。通过config-server可以连接到git，访问其中的资源和配置。
  cloud:
    config:
      server:
        git:
          # uri选gitee上https的克隆链接
          uri: https://gitee.com/loubth/springcloud-config.git
          skip-ssl-validation: true